import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeToggle from "@/components/theme-toggle";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Native Modal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <RootProvider>
          <ThemeProvider enableSystem attribute="class" defaultTheme="dark" disableTransitionOnChange>
            <div data-vaul-drawer-wrapper="">
              <div className="absolute right-4 top-4 z-50 flex items-center gap-2 max-lg:hidden">
                <ThemeToggle />
              </div>
              {children}
            </div>
          </ThemeProvider>
        </RootProvider>
      </body>
    </html>
  );
}
